http://localhost:4000/

###

http://localhost:4000/status

###

http://localhost:5000/blocks

###
http://localhost:4000/wallet

###

POST http://localhost:4000/blocks

{
    "message": "Data for my block"
}

###

http://localhost:4000/balance/5f019863c26769e62b30aa846648218bd212670d223cfb15b6c72d4e5528b485feb45e944035b24f5886f992a6036ee7466ac58a6033ad5e54d8e5d13a5c1ffa


###
http://localhost:4000/mempool


###
POST http://localhost:4000/transactions

{
    "to":"solhui",
    "amount": 30
}

###
POST http://localhost:2000/peers

{
    "address": "127.0.0.1",
    "port": "5000"
}

###
http://localhost:5000/peers